import React from "react"

export default {
    title: {
        en_US: "About me",
        de_DE: "Über mich",
        pl_PL: "O mnie"
    },
    description: {
        en_US: <React.Fragment><p className="mono">Lorem ad ullamco adipisicing labore anim est proident reprehenderit dolor sunt. In officia id do cupidatat voluptate exercitation consequat sunt et quis irure non ullamco magna. Do nisi mollit pariatur mollit est culpa et ut tempor esse ullamco ullamco. Commodo dolore ipsum aute proident amet nisi et cillum id consequat sit est non.</p><p className="mono">Laboris qui ex cillum exercitation cillum esse elit ipsum excepteur cupidatat duis nulla et ut. Do adipisicing voluptate nostrud ex adipisicing laboris sint exercitation consequat officia minim tempor ex. Nisi irure eu culpa fugiat Lorem. Veniam eiusmod enim ad dolore incididunt velit eiusmod in amet sint incididunt dolor ad consequat. Non magna in reprehenderit eu amet amet occaecat deserunt cupidatat deserunt.</p><p className="mono">Officia mollit enim labore magna voluptate consequat eu dolore reprehenderit reprehenderit officia culpa do. Cillum duis adipisicing anim adipisicing dolore laboris aute occaecat cillum proident. Consectetur irure exercitation fugiat deserunt occaecat ea ex nostrud ullamco aliquip dolor. Anim dolore sit anim aliqua labore ut nisi et nulla aliquip. Cupidatat consequat dolor labore aliqua velit tempor cupidatat exercitation qui sit quis. Pariatur reprehenderit do proident cupidatat. Non nulla id ad esse ea cupidatat ex magna laborum.</p></React.Fragment>,
        de_DE: <React.Fragment><p className="mono">Lorem ad ullamco adipisicing labore anim est proident reprehenderit dolor sunt. In officia id do cupidatat voluptate exercitation consequat sunt et quis irure non ullamco magna. Do nisi mollit pariatur mollit est culpa et ut tempor esse ullamco ullamco. Commodo dolore ipsum aute proident amet nisi et cillum id consequat sit est non.</p><p className="mono">Laboris qui ex cillum exercitation cillum esse elit ipsum excepteur cupidatat duis nulla et ut. Do adipisicing voluptate nostrud ex adipisicing laboris sint exercitation consequat officia minim tempor ex. Nisi irure eu culpa fugiat Lorem. Veniam eiusmod enim ad dolore incididunt velit eiusmod in amet sint incididunt dolor ad consequat. Non magna in reprehenderit eu amet amet occaecat deserunt cupidatat deserunt.</p><p className="mono">Officia mollit enim labore magna voluptate consequat eu dolore reprehenderit reprehenderit officia culpa do. Cillum duis adipisicing anim adipisicing dolore laboris aute occaecat cillum proident. Consectetur irure exercitation fugiat deserunt occaecat ea ex nostrud ullamco aliquip dolor. Anim dolore sit anim aliqua labore ut nisi et nulla aliquip. Cupidatat consequat dolor labore aliqua velit tempor cupidatat exercitation qui sit quis. Pariatur reprehenderit do proident cupidatat. Non nulla id ad esse ea cupidatat ex magna laborum.</p></React.Fragment>,
        pl_PL: <React.Fragment><p className="mono">Lorem ad ullamco adipisicing labore anim est proident reprehenderit dolor sunt. In officia id do cupidatat voluptate exercitation consequat sunt et quis irure non ullamco magna. Do nisi mollit pariatur mollit est culpa et ut tempor esse ullamco ullamco. Commodo dolore ipsum aute proident amet nisi et cillum id consequat sit est non.</p><p className="mono">Laboris qui ex cillum exercitation cillum esse elit ipsum excepteur cupidatat duis nulla et ut. Do adipisicing voluptate nostrud ex adipisicing laboris sint exercitation consequat officia minim tempor ex. Nisi irure eu culpa fugiat Lorem. Veniam eiusmod enim ad dolore incididunt velit eiusmod in amet sint incididunt dolor ad consequat. Non magna in reprehenderit eu amet amet occaecat deserunt cupidatat deserunt.</p><p className="mono">Officia mollit enim labore magna voluptate consequat eu dolore reprehenderit reprehenderit officia culpa do. Cillum duis adipisicing anim adipisicing dolore laboris aute occaecat cillum proident. Consectetur irure exercitation fugiat deserunt occaecat ea ex nostrud ullamco aliquip dolor. Anim dolore sit anim aliqua labore ut nisi et nulla aliquip. Cupidatat consequat dolor labore aliqua velit tempor cupidatat exercitation qui sit quis. Pariatur reprehenderit do proident cupidatat. Non nulla id ad esse ea cupidatat ex magna laborum.</p></React.Fragment>,
    }
}